version: '3'
services:
  chrome:
    image: ghcr.io/browserless/chromium
    environment:
      - CONCURRENT=10
      - TIMEOUT=30000

  pdf-service:
    build: .
    ports:
      - "3004:3004"
    volumes:
      - ../data/uploads:/app/data/uploads