version: '3'
services:
  chrome:
    image: ghcr.io/browserless/chromium
    environment:
      - MAX_CONCURRENT_SESSIONS=10
      - CONNECTION_TIMEOUT=30000
      - KEEP_ALIVE=true

  pdf-service:
    build: .
    ports:
      - "3004:3004"
    volumes:
      - ../data/uploads:/app/data/uploads